/**
 * @file        skate3_audio_census_all.cpp
 * @brief       Counting hooks on every audio-thread function that has no native port yet
 *
 * GENERATED by probe/ports/queue.py manifests from probe/ports/queue.json. Do not edit.
 *
 * Each hook counts the call, dumps the entry registers and thread name for the first four
 * calls, and forwards to the original. Cvar-gated (`skate3_audio_port_census`), so it costs a
 * load and a branch when off. As functions gain a port file the generator drops them from
 * here, because a second definition of the same symbol is a link error.
 */
#include "skate3_audio_port.h"

namespace {
constexpr const char* kNames[] = {
};
constexpr size_t kCount = sizeof(kNames) / sizeof(kNames[0]);
skate3::audio::CensusSlot g_slots[kCount ? kCount : 1]{};
skate3::audio::CensusTable g_table{kNames, g_slots, kCount};
struct RegisterOnLoad {
  RegisterOnLoad() { skate3::audio::RegisterCensusTable(g_table); }
} g_register;
}  // namespace

#define SKATE3_CENSUS_ALL(index, name)                              \
  extern "C" REX_FUNC(name) {                                       \
    skate3::audio::CensusHit(g_table, index, ctx);                  \
    __imp__##name(ctx, base);                                       \
  }

