/**
 * @file        skate3_audio_census_all.cpp
 * @brief       Counting hooks on every audio-thread function that has no native port yet
 *
 * GENERATED by probe/ports/queue.py manifests from probe/ports/queue.json. Do not edit.
 *
 * Each hook counts the call, dumps the entry registers and thread name for the first four
 * calls, and forwards to the original. Cvar-gated (`skate3_audio_port_census`), so it costs a
 * load and a branch when off. As functions gain a port file the generator drops them from
 * here, because a second definition of the same symbol is a link error.
 */
#include "skate3_audio_port.h"

namespace {
constexpr const char* kNames[] = {
    "sub_82B298E0",
    "sub_82B2F590",
    "sub_82B2F8C0",
    "sub_82B30C50",
    "sub_82B34278",
    "sub_82B45788",
    "sub_82B45C50",
    "sub_82B460A0",
    "sub_82B50B80",
};
constexpr size_t kCount = sizeof(kNames) / sizeof(kNames[0]);
skate3::audio::CensusSlot g_slots[kCount ? kCount : 1]{};
skate3::audio::CensusTable g_table{kNames, g_slots, kCount};
struct RegisterOnLoad {
  RegisterOnLoad() { skate3::audio::RegisterCensusTable(g_table); }
} g_register;
}  // namespace

#define SKATE3_CENSUS_ALL(index, name)                              \
  extern "C" REX_FUNC(name) {                                       \
    skate3::audio::CensusHit(g_table, index, ctx);                  \
    __imp__##name(ctx, base);                                       \
  }

SKATE3_CENSUS_ALL(0, sub_82B298E0)
SKATE3_CENSUS_ALL(1, sub_82B2F590)
SKATE3_CENSUS_ALL(2, sub_82B2F8C0)
SKATE3_CENSUS_ALL(3, sub_82B30C50)
SKATE3_CENSUS_ALL(4, sub_82B34278)
SKATE3_CENSUS_ALL(5, sub_82B45788)
SKATE3_CENSUS_ALL(6, sub_82B45C50)
SKATE3_CENSUS_ALL(7, sub_82B460A0)
SKATE3_CENSUS_ALL(8, sub_82B50B80)
