/**
 * @file        skate3_audio_census_all.cpp
 * @brief       Counting hooks on every audio-thread function that has no native port yet
 *
 * GENERATED by probe/ports/queue.py manifests from probe/ports/queue.json. Do not edit.
 *
 * Each hook counts the call, dumps the entry registers and thread name for the first four
 * calls, and forwards to the original. Cvar-gated (`skate3_audio_port_census`), so it costs a
 * load and a branch when off. As functions gain a port file the generator drops them from
 * here, because a second definition of the same symbol is a link error.
 */
#include "skate3_audio_port.h"

namespace {
constexpr const char* kNames[] = {
    "sub_82B1DC00",
    "sub_82B21D98",
    "sub_82B222D8",
    "sub_82B225A0",
    "sub_82B22898",
    "sub_82B26740",
    "sub_82B29288",
    "sub_82B298E0",
    "sub_82B2C658",
    "sub_82B2C8F0",
    "sub_82B2F590",
    "sub_82B2F798",
    "sub_82B2F8C0",
    "sub_82B305C0",
    "sub_82B30C50",
    "sub_82B31480",
    "sub_82B31EE0",
    "sub_82B32DC8",
    "sub_82B335A8",
    "sub_82B33780",
    "sub_82B34278",
    "sub_82B376B8",
    "sub_82B426D0",
    "sub_82B42C98",
    "sub_82B43D78",
    "sub_82B444C0",
    "sub_82B44858",
    "sub_82B45788",
    "sub_82B45C50",
    "sub_82B460A0",
    "sub_82B468C0",
    "sub_82B470D0",
    "sub_82B474B8",
    "sub_82B47A68",
    "sub_82B482F8",
    "sub_82B48530",
    "sub_82B49100",
    "sub_82B4FE40",
    "sub_82B50100",
    "sub_82B50380",
    "sub_82B50B80",
};
constexpr size_t kCount = sizeof(kNames) / sizeof(kNames[0]);
skate3::audio::CensusSlot g_slots[kCount ? kCount : 1]{};
skate3::audio::CensusTable g_table{kNames, g_slots, kCount};
struct RegisterOnLoad {
  RegisterOnLoad() { skate3::audio::RegisterCensusTable(g_table); }
} g_register;
}  // namespace

#define SKATE3_CENSUS_ALL(index, name)                              \
  extern "C" REX_FUNC(name) {                                       \
    skate3::audio::CensusHit(g_table, index, ctx);                  \
    __imp__##name(ctx, base);                                       \
  }

SKATE3_CENSUS_ALL(0, sub_82B1DC00)
SKATE3_CENSUS_ALL(1, sub_82B21D98)
SKATE3_CENSUS_ALL(2, sub_82B222D8)
SKATE3_CENSUS_ALL(3, sub_82B225A0)
SKATE3_CENSUS_ALL(4, sub_82B22898)
SKATE3_CENSUS_ALL(5, sub_82B26740)
SKATE3_CENSUS_ALL(6, sub_82B29288)
SKATE3_CENSUS_ALL(7, sub_82B298E0)
SKATE3_CENSUS_ALL(8, sub_82B2C658)
SKATE3_CENSUS_ALL(9, sub_82B2C8F0)
SKATE3_CENSUS_ALL(10, sub_82B2F590)
SKATE3_CENSUS_ALL(11, sub_82B2F798)
SKATE3_CENSUS_ALL(12, sub_82B2F8C0)
SKATE3_CENSUS_ALL(13, sub_82B305C0)
SKATE3_CENSUS_ALL(14, sub_82B30C50)
SKATE3_CENSUS_ALL(15, sub_82B31480)
SKATE3_CENSUS_ALL(16, sub_82B31EE0)
SKATE3_CENSUS_ALL(17, sub_82B32DC8)
SKATE3_CENSUS_ALL(18, sub_82B335A8)
SKATE3_CENSUS_ALL(19, sub_82B33780)
SKATE3_CENSUS_ALL(20, sub_82B34278)
SKATE3_CENSUS_ALL(21, sub_82B376B8)
SKATE3_CENSUS_ALL(22, sub_82B426D0)
SKATE3_CENSUS_ALL(23, sub_82B42C98)
SKATE3_CENSUS_ALL(24, sub_82B43D78)
SKATE3_CENSUS_ALL(25, sub_82B444C0)
SKATE3_CENSUS_ALL(26, sub_82B44858)
SKATE3_CENSUS_ALL(27, sub_82B45788)
SKATE3_CENSUS_ALL(28, sub_82B45C50)
SKATE3_CENSUS_ALL(29, sub_82B460A0)
SKATE3_CENSUS_ALL(30, sub_82B468C0)
SKATE3_CENSUS_ALL(31, sub_82B470D0)
SKATE3_CENSUS_ALL(32, sub_82B474B8)
SKATE3_CENSUS_ALL(33, sub_82B47A68)
SKATE3_CENSUS_ALL(34, sub_82B482F8)
SKATE3_CENSUS_ALL(35, sub_82B48530)
SKATE3_CENSUS_ALL(36, sub_82B49100)
SKATE3_CENSUS_ALL(37, sub_82B4FE40)
SKATE3_CENSUS_ALL(38, sub_82B50100)
SKATE3_CENSUS_ALL(39, sub_82B50380)
SKATE3_CENSUS_ALL(40, sub_82B50B80)
